# Background {-}

## Statistical Surveys {-}
States and Tribes are required by the Clean Water Act (CWA) to periodically report on the condition of all their waters. The States and Tribes typically monitor at targeted sites and can make scientifically-defensible statements about the condition of their waters only at these sites. Typically, this covers only a small percentage of the total waters. Ideally, an organization would survey an entire population, otherwise known as a census, to perfectly reflect the condition of a resource. However, this is rarely possible and organizations are forced to implement a __Statistical Survey (Probabilistic) Design__ to randomly select a subset of the population to reduce the cost and effort. In such a design, each sampling site represents a specific portion of the total resource or population of interest such as all river and stream length in the nation. Because of the statistical nature of site selection, results from the sample population can be extrapolated to the entire population. For this reason, probability surveys are well suited for making unbiased assessments of the condition of an entire resource across large geographic areas with a known confidence.


## NARS and Monitoring Initiative Funds {-}
The Environmental Protection Agency (EPA) utilizes statistical survey designs in the National Aquatic Resource Surveys (NARS). NARS provides statistically valid national assessments of the condition of the nation’s waters (streams and rivers, lakes, coastal waters, and wetlands). EPA encourages states to implement a statistical survey in their monitoring program to provide comprehensive statements about statewide water quality conditions (in line with §305(b) reporting).
 
Monitoring Initiative funds are allocated to states, eligible interstate agencies, and eligible tribes using a formula that targets funds to enhance monitoring strategies and develop statistically valid reports on water condition. EPA, states and other partners collaborate to design the National Aquatic Resource Surveys, which cover the continental United States. For each sampling site selected through the survey design that falls within their jurisdiction, a state, eligible interstate agency, or eligible tribe receives approximately $8,000. Alaska, Hawaii, and the territories are not included in the National Aquatic Resource Surveys, but receive some of this funding for statistical survey projects.

The requirements for receiving monitoring initiative funds are:

__1. Implementing a statistical survey design that provides condition estimates for a population of waters (e.g., streams, rivers, lakes, coastal waters, or wetlands) of the state based on an unbiased, representative sample of a subset of those waters. If they choose not to they must describe the program capacity development activities they are proposing and link them to their monitoring strategy.__

__2. Participate in the national/regional scale surveys (which may just be agreement to receive in-kind assistance).__

__3. Report the results of the states scale survey, preferably as a component of the state’s Integrated Report (narrative form) and/or in the probability survey module of ATTAINS.__

## Leveraging NARS for Partners {-}

EPA encourages states, tribal nations, and other partners to leverage implementation of the NARS whether through the addition of indicators of special interest, sampling additional sites to achieve state-level or other program monitoring objectives or integrating their monitoring program with NARS. 



### Planning for an Intensification  {-}

EPA defines the addition of sites to the NARS as an intensification. Taking on an intensification typically requires significant coordination between the state, tribe or other groups involved and EPA to make the project a success. There are several things to think about when considering an intensification such as your overall objectives, costs, where the funding will come from and who will conduct the work. Below is more detail on these and other items. If you have decided that an intensification might be feasible, we encourage you to reach out to your Regional Monitoring Coordinator to talk through the next steps in planning and logistics. 

__1.	Cost__ - The cost of the intensification is the responsibility of the interested party. States may be able to use Part A Monitoring Initiative funds for intensifications, but the Part B NARS Monitoring Initiative funds allocated for  national scale sites are not generally  sufficient to accommodate intensifications. Check with your regional points of contacts and grants officers for potential funding sources.

__2. 	When do you need to start planning?__ - Ideally, planning starts a year and a half to two years ahead of the field season so the intensification design can be included in the national design and to accommodate state and tribal requests for EPA contractor services.

__3.	Who should you contact first?__ - Please reach out to your Regional Monitoring Coordinator to discuss the feasibility of your intensification.

__4)	Who is involved in the planning process (may not all be involved during initial discussions of feasibility)?__  
      a)	State, tribe, territories or other groups interested in intensification/special study
      b)	Regional monitoring coordinator/POC 
      c)	Technical lead of the survey involved
      d)	Logistics lead from HQs
      e)	NARS team leader
      f)	Grants Officer (optional; may want to include so they are aware of possible request)
__5)	What to consider prior to talking with persons listed above:__
      a)	Identify the players from the intensification
      b)	Identify objective of the intensification/special project
            (1)	Will the intensification rely on previously created sites within the national design?
                (2)	Will the intensification need a new sample design that will fit within the scope of the NARS design?
      c)	Identify issues related to:
            (1)	Target population of interest; subpopulations of interest – needs to be defined by intensification team
            (2)	What is the sample frame? (Identified by intensification team)
            (3)	Which indicators are of interest?
            (4)	Number of samples?
            (5)	Who will do the field work? Will it require additional training or specialized personnel?
            (6)	Who will do the lab work?
            (7)	What is the timeframe of this intensification? Will it be the same or different from national survey?
            (8)	What is the expected analytical approach? Will you need assistance conducting this analysis? What will the end products be?
                (i)	  Timeframe of data analysis and QC of data
                (ii)	Development of write-ups of findings
                (iii)	Where will the data and results be posted?
                (iv)	Where are resources coming from? 
__6)	Following up on this call, other discussions will be needed:__
      a)	Specialized designs: conversations with Corvallis design team.
      b)	NARS field App and NARS IM data storage questions: Conversation with Karen Blocksom; 
      c)	Logistics contractor: arranging of training of field crews, shipping and handling of samples;
      d)	NARS Team Lead and Site Evaluation Coordinator
__7)	Additional considerations:__
      EPA encourages collection of all NARS indicators when possible so that the data can be used in national assessment as well.
      a)	When all indicators are collected using NARS methods (in addition to other items the organizations may be interested in), EPA currently            supports the following:
            (1)	Providing site kits for the extra sites.
            (2)	Shipping of samples to the national labs (NARS will not pay for analyses of extra samples nor does the NARS program pay for                        shipping to state or other labs).
            (3)	Use of field form app (note, at this time customization of the app is difficult for EPA from a workload, funding and technology                    perspective; while EPA is happy to discuss specializations, we may not be able to accommodate them because we have to make sure                   the primary app is functioning, and data can flow into NARS IM).
            (4)	Data management for the NARS data.  EPA cannot customize NARS IM to pull in other data. 
            (5)	Data analysis using NARS approaches (note that in areas outside the continental U.S., this could require discussion because the                    resource itself may be substantially different and require different analyses or benchmarks for which we may/may not have                          sufficient data to address.
            (6)	Training for field crews (on NARS methods)
      b)	When all indicators are not included, EPA has generally not provided site kits or shipping for the extra sites.







Sample frames for NARS and states may differ due to different target populations, source material, and state knowledge leading to improvements.
















